In [60]:
from tensorflow.keras.datasets   import boston_housing , mnist , fashion_mnist , reuters
from tensorflow.keras.models     import Sequential , clone_model , Model , load_model
from tensorflow.keras.layers     import Dense , Activation , InputLayer , Flatten , Input , BatchNormalization , Dropout , Embedding
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

# CNN
from tensorflow.keras.layers     import Conv2D , MaxPooling2D , AveragePooling2D

# RNN
from tensorflow.keras.layers     import SimpleRNN , LSTM


from tensorflow.keras            import optimizers  
from tensorflow.keras.callbacks  import EarlyStopping , ModelCheckpoint , Callback
from tensorflow.keras.optimizers import SGD , Adam , RMSprop

# 이미지 로드
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator 

# 자연어 처리
from tensorflow.keras.preprocessing.text          import Tokenizer
from tensorflow.keras.preprocessing.sequence      import pad_sequences

from keras.utils.np_utils      import to_categorical

from sklearn.datasets          import load_iris , load_breast_cancer , load_digits
from sklearn.model_selection   import train_test_split
from sklearn.metrics           import accuracy_score
import matplotlib.pyplot as plt

import numpy  as np
import pandas as pd


#### Recurrent Neural Network(RNN)
- 데이터가 입력되는 순서가 중요한 역할을 하는 순차형 정보를 처리하기위한 구조

In [3]:
print('rnn 모델 데이터 입력 - ') 

# batch_size : 모델이 학습할 때 고려되는 인스턴스의 갯수
# timesteps  : 인풋 시퀀스의 갯수
# input_dim  : 인풋 시퀀스의 차원(feature 수) 

x = np.array( [ [[1,2,3],[4,5,6]] , 
                [[1,2,3],[4,5,6]] , 
                [[1,2,3],[4,5,6]] ])

print('batch_size , timesteps , input_dim = ' , x.shape)


rnn 모델 데이터 입력 - 
batch_size , timesteps , input_dim =  (3, 2, 3)


In [29]:
rnn = SimpleRNN(50)(Input(shape=(10, 30))) 
rnn.shape


TensorShape([None, 50])

In [6]:
rnn = SimpleRNN(50 , return_sequences= True )(Input(shape=(10, 30))) 
rnn.shape

TensorShape([None, 10, 50])

In [10]:
rnn = SimpleRNN(50 , return_sequences= True , return_state = True )(Input(shape=(10, 30))) 
print('shape of output - ' , rnn[0].shape)
print('shape of state  - ' , rnn[1].shape)

shape of output -  (None, 10, 50)
shape of state  -  (None, 50)


#### LSTM(Long Short-Term Memory)


In [12]:
lstm = LSTM(50 , return_sequences= True , return_state = True )(Input(shape=(10, 30))) 
print('shape of output        - ' , lstm[0].shape)
print('shape of hidden state  - ' , lstm[1].shape)
print('shape of cell   state  - ' , lstm[2].shape)

shape of output        -  (None, 10, 50)
shape of hidden state  -  (None, 50)
shape of cell   state  -  (None, 50)


#### 순환신경망 만들기 - reuters

In [34]:
(X_train , y_train) , (X_test , y_test) = reuters.load_data(num_words = 30000 , 
                                                            maxlen    = 100    , 
                                                            test_split = 0.3 ) 
(X_train.shape , y_train.shape) , (X_test.shape , y_test.shape)

(((4180,), (4180,)), ((1792,), (1792,)))

In [ ]:
X_train[0]

In [36]:
y_train[:100]

array([ 3,  4,  3,  3,  3,  4,  8,  3,  3, 21,  4,  3,  3,  3,  1,  3,  3,
        3, 11, 16, 18, 25, 19,  3,  4,  3,  3,  4,  3,  4,  3, 35,  8,  4,
        3, 10,  4,  4,  3,  3,  3,  3,  3,  4,  4,  4,  2,  3,  1, 19,  4,
        3,  4,  4,  4,  3,  3,  3, 11,  3, 13,  1,  3, 21, 19,  4,  3,  3,
        3,  4,  4,  3,  6,  3,  4,  3,  4,  7,  3, 19,  8,  3,  4,  4,  3,
        3, 16,  3,  4,  1,  3,  3,  3,  3,  4,  3,  3, 13,  3,  1])

In [37]:
X_train = pad_sequences(X_train , padding = 'post')
X_test  = pad_sequences(X_test , padding = 'post')

In [38]:
X_train[0]

array([    1, 27595, 28842,     8,    43,    10,   447,     5,    25,
         207,   270,     5,  3095,   111,    16,   369,   186,    90,
          67,     7,    89,     5,    19,   102,     6,    19,   124,
          15,    90,    67,    84,    22,   482,    26,     7,    48,
           4,    49,     8,   864,    39,   209,   154,     6,   151,
           6,    83,    11,    15,    22,   155,    11,    15,     7,
          48,     9,  4579,  1005,   504,     6,   258,     6,   272,
          11,    15,    22,   134,    44,    11,    15,    16,     8,
         197,  1245,    90,    67,    52,    29,   209,    30,    32,
         132,     6,   109,    15,    17,    12,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0],
      dtype=int32)

In [39]:
(X_train.shape , y_train.shape) , (X_test.shape , y_test.shape)

(((4180, 99), (4180,)), ((1792, 99), (1792,)))

In [40]:
print('rnn 은 input shape으로 2개의 파라미터를 받아야 하므로 차원변환 - ') 
X_train = np.array(X_train).reshape( (X_train.shape[0] , X_train.shape[1] , 1)) 
X_test  = np.array(X_test).reshape( (X_test.shape[0] , X_test.shape[1] , 1)) 

rnn 은 input shape으로 2개의 파라미터를 받아야 하므로 차원변환 - 


In [41]:
(X_train.shape , y_train.shape) , (X_test.shape , y_test.shape)

(((4180, 99, 1), (4180,)), ((1792, 99, 1), (1792,)))

In [42]:
y_data = np.concatenate((y_train , y_test))

y_data = to_categorical(y_data)


In [43]:
(X_train.shape , y_train.shape) , (X_test.shape , y_test.shape)

(((4180, 99, 1), (4180,)), ((1792, 99, 1), (1792,)))

In [44]:
y_train = y_data[ : 4180]
y_test  = y_data[4180 : ]

In [45]:
(X_train.shape , y_train.shape) , (X_test.shape , y_test.shape)

(((4180, 99, 1), (4180, 46)), ((1792, 99, 1), (1792, 46)))

In [73]:
def vanilla_rnn() :

  model = Sequential()
  model.add( SimpleRNN(50 , input_shape = (99, 1) , return_sequences = False )) 

  model.add( Dense(46) )
  model.add( Activation('softmax'))

  model.compile(optimizer = Adam(lr = 0.001) , 
                loss      = 'categorical_crossentropy' , 
                metrics   = ['accuracy']) 
  return model 

def stacked_vanilla_rnn() :

  model = Sequential()

  model.add( SimpleRNN(50 , input_shape = (99, 1) , return_sequences = True )) 
  model.add( SimpleRNN(50 , return_sequences = False )) 

  model.add( Dense(46) )
  model.add( Activation('softmax'))

  model.compile(optimizer = Adam(lr = 0.001) , 
                loss      = 'categorical_crossentropy' , 
                metrics   = ['accuracy']) 
  return model 

def stacked_vanilla_lstm() :

  model = Sequential()

  model.add( LSTM(50 , input_shape = (99, 1) , return_sequences = True )) 
  model.add( LSTM(40 , return_sequences = False)) 

  model.add( Dense(46) )
  model.add( Activation('softmax'))

  model.compile(optimizer = Adam(lr = 0.001) , 
                loss      = 'categorical_crossentropy' , 
                metrics   = ['accuracy']) 
  return model 

In [67]:
model = KerasClassifier(build_fn   = vanilla_rnn , 
                        epochs     = 5 , 
                        batch_size = 50 , 
                        verbose    = 1)
model.fit(X_train , y_train)

Epoch 1/5


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


84/84 [==============================] - 11s 115ms/step - loss: 2.2878 - accuracy: 0.4074
Epoch 2/5
84/84 [==============================] - 10s 119ms/step - loss: 1.8881 - accuracy: 0.5012
Epoch 3/5
84/84 [==============================] - 10s 117ms/step - loss: 1.8835 - accuracy: 0.5010
Epoch 4/5
84/84 [==============================] - 10s 118ms/step - loss: 1.8817 - accuracy: 0.5019
Epoch 5/5
84/84 [==============================] - 10s 117ms/step - loss: 1.8803 - accuracy: 0.5000


In [54]:
y_pred = model.predict(X_test)
y_pred

array([3, 3, 3, ..., 3, 3, 4])

In [58]:
y_test_ = np.argmax(y_test , axis = 1)
y_test_

array([4, 4, 3, ..., 3, 3, 3])

In [61]:
accuracy_score(y_pred , y_test_)

0.5061383928571429

In [ ]:
model = KerasClassifier(build_fn   = stacked_vanilla_rnn , 
                        epochs     = 50 , 
                        batch_size = 50 , 
                        verbose    = 1)
model.fit(X_train , y_train)

In [74]:
model = KerasClassifier(build_fn   = stacked_vanilla_lstm , 
                        epochs     = 50 , 
                        batch_size = 50 , 
                        verbose    = 1)
model.fit(X_train , y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  after removing the cwd from sys.path.


Epoch 1/50


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


84/84 [==============================] - 38s 40ms/step - loss: 2.3257 - accuracy: 0.4911
Epoch 2/50
84/84 [==============================] - 3s 40ms/step - loss: 1.8397 - accuracy: 0.5043
Epoch 3/50
84/84 [==============================] - 3s 40ms/step - loss: 1.6956 - accuracy: 0.5766
Epoch 4/50
84/84 [==============================] - 3s 40ms/step - loss: 1.5520 - accuracy: 0.6273
Epoch 5/50
84/84 [==============================] - 3s 40ms/step - loss: 1.5222 - accuracy: 0.6440
Epoch 6/50
84/84 [==============================] - 3s 40ms/step - loss: 1.5071 - accuracy: 0.6474
Epoch 7/50
84/84 [==============================] - 3s 40ms/step - loss: 1.5038 - accuracy: 0.6440
Epoch 8/50
84/84 [==============================] - 3s 40ms/step - loss: 1.4911 - accuracy: 0.6502
Epoch 9/50
84/84 [==============================] - 3s 40ms/step - loss: 1.4898 - accuracy: 0.6512
Epoch 10/50
84/84 [==============================] - 3s 40ms/step - loss: 1.4779 - accuracy: 0.6526
Epoch 11/50
84/84 [