#### Pandas

- 데이터 조작을 위한 패키지
- 데이터 타입 : Series(시계열) , DataFrame(표, 테이블)
- Series -> vector , DataFrame -> N-D Array
- Series : index + values 

In [209]:
import numpy  as np
import pandas as pd

import warnings
warnings.filterwarnings(action='ignore')

from datetime import date, datetime, timedelta
from dateutil.parser import parse

import json
import urllib 


print('numpy  version - ' , np.__version__)
print('pandas version - ' , pd.__version__)

numpy  version -  1.20.3
pandas version -  1.3.4


- Series 생성

In [19]:
print('list 이용한 생성 - ')
print()

prices = pd.Series(['4000', 3000, 3500, 2000])
print(prices)

print()
print('type - ' , type(prices))

print()
print('index , values - ')
print('index  - ' , prices.index)
print('value  - ' , prices.values , type(prices.values))
prices = prices.astype('int32')
print('dtype  - ' , prices.dtype)

print()
print('원하는 값을 찾는다면? - 인덱싱이 가능하다 ')
print('마이너스 인덱싱은 불가하다')
print()
print('indexing - '   , prices[0] )
print('slicing  - \n' , prices[ : 3 ])
# print('indexing - '   , prices[-1]) -- error


list 이용한 생성 - 

0    4000
1    3000
2    3500
3    2000
dtype: object

type -  <class 'pandas.core.series.Series'>

index , values - 
index  -  RangeIndex(start=0, stop=4, step=1)
value  -  ['4000' 3000 3500 2000] <class 'numpy.ndarray'>
dtype  -  int32

원하는 값을 찾는다면? - 인덱싱이 가능하다 
마이너스 인덱싱은 불가하다

indexing -  4000
slicing  - 
 0    4000
1    3000
2    3500
dtype: int32


In [38]:
print('사용자 정의 인덱스 부여가 가능하다 - ') 

prices = pd.Series([4000, 3000, 3500, 2000] , 
                    index = ['a', 'b', 'c', 'd']   )

print(prices)
print()
print(prices[0] , type(prices[0]) , prices['a'] )

print()
print(prices['a' : 'c'] , type(prices['a' : 'c']))

print()
print('인덱스가 존재하는지 - ' , 'a' in prices , 0 in prices)

print(prices.index)

print()
print('인덱스를 활용한 데이터 변경 - ')
prices['a'] = 10000
print()
print( prices )

print()
print('데이터 추가 가능 - ')
prices['e'] = 6000
print( prices )

print()
print('데이터 삭제 - ')
del prices['e']
print( prices )


사용자 정의 인덱스 부여가 가능하다 - 
a    4000
b    3000
c    3500
d    2000
dtype: int64

4000 <class 'numpy.int64'> 4000

a    4000
b    3000
c    3500
dtype: int64 <class 'pandas.core.series.Series'>

인덱스가 존재하는지 -  True False
Index(['a', 'b', 'c', 'd'], dtype='object')

인덱스를 활용한 데이터 변경 - 

a    10000
b     3000
c     3500
d     2000
dtype: int64

데이터 추가 가능 - 
a    10000
b     3000
c     3500
d     2000
e     6000
dtype: int64

데이터 삭제 - 
a    10000
b     3000
c     3500
d     2000
dtype: int64


In [52]:

prices = pd.Series([4000, 3000, 3500, 2000])
print()
print('벡터화 연산이 가능하다 - ') 
print( prices * 10 )
print( prices )

print()
print('조건식을 활용 할 수 있다 - ')

prices[ prices > 3000 ]


벡터화 연산이 가능하다 - 
0    40000
1    30000
2    35000
3    20000
dtype: int64
0    4000
1    3000
2    3500
3    2000
dtype: int64

조건식을 활용 할 수 있다 - 


0    4000
2    3500
dtype: int64

In [48]:
print('dict , tuple , set  생성이 가능 -')
print()

person = pd.Series({ 'name' : '임정섭' , 'age' : 25 })
print( person )
print('index - ' , person.index)
print('value - ' , person.values)

print()
print()
ages = pd.Series( (10, 20, 30) ) 
print( ages )
print('index - ' , ages.index)
print('value - ' , ages.values)

print()
print('set 은 주의하셔야 한다 - ')
ages = pd.Series( list( {10, 20, 30} ) ) 
print( ages )
print('index - ' , ages.index)
print('value - ' , ages.values)



dict , tuple , set  생성이 가능 -

name    임정섭
age      25
dtype: object
index -  Index(['name', 'age'], dtype='object')
value -  ['임정섭' 25]


0    10
1    20
2    30
dtype: int64
index -  RangeIndex(start=0, stop=3, step=1)
value -  [10 20 30]

set 은 주의하셔야 한다 - 
0    10
1    20
2    30
dtype: int64
index -  RangeIndex(start=0, stop=3, step=1)
value -  [10 20 30]


- 인덱스의 라벨은 정수, 문자, 날짜, 시간

In [50]:
tmp = pd.Series([1,2,3,4,5],
                index = ['강남', '서초', '방배', '동작', '광진'] )

tmp.name = '특정한 의미를 부여할 수 있다'
tmp.index.name= '구 구별' 
tmp

구 구별
강남    1
서초    2
방배    3
동작    4
광진    5
Name: 특정한 의미를 부여할 수 있다, dtype: int64

In [55]:
tmp = pd.Series( range(10, 21) , dtype = 'f') 
tmp

0     10.0
1     11.0
2     12.0
3     13.0
4     14.0
5     15.0
6     16.0
7     17.0
8     18.0
9     19.0
10    20.0
dtype: float32

In [56]:
print( tmp * 10)

0     100.0
1     110.0
2     120.0
3     130.0
4     140.0
5     150.0
6     160.0
7     170.0
8     180.0
9     190.0
10    200.0
dtype: float32


In [57]:
print( tmp[ tmp%2 == 0 ] )

0     10.0
2     12.0
4     14.0
6     16.0
8     18.0
10    20.0
dtype: float32


In [68]:
print('날짜와 시간을 인덱스로 활용한다면? - ')

day = datetime(2022, 3, 25)
print( day + timedelta(days=1) )

날짜와 시간을 인덱스로 활용한다면? - 
2022-03-26 00:00:00


In [64]:
print('[실습] 평균이 50이고 편차 5인 정규분포 데이터를 10일간 만들고 싶다면? - ') 
print(' np.random.normal(50, 5, 10) ')

[실습] 평균이 50이고 편차 5인 정규분포 데이터를 10일간 만들고 싶다면? - 


In [65]:
np.random.normal(50, 5, 10)

array([51.4017708 , 49.21376019, 53.24921743, 58.33235564, 51.81028354,
       57.85904754, 50.19999076, 52.84232565, 51.71185837, 53.63122399])

In [72]:
factory01 = pd.Series( np.random.normal(50, 5, 10) , 
                       index = [ day + timedelta(days = d) for d in range(10) ])
factory02 = pd.Series( np.random.normal(50, 5, 10) , 
                       index = [ day + timedelta(days = d) for d in range(10) ])
 

In [73]:
factory01

2022-03-25    47.886229
2022-03-26    48.510604
2022-03-27    45.241834
2022-03-28    49.026242
2022-03-29    51.285867
2022-03-30    41.314475
2022-03-31    46.288635
2022-04-01    51.330821
2022-04-02    53.208003
2022-04-03    43.691562
dtype: float64

In [74]:
factory02

2022-03-25    44.626298
2022-03-26    38.750652
2022-03-27    53.328332
2022-03-28    55.554849
2022-03-29    49.095515
2022-03-30    50.116014
2022-03-31    43.919757
2022-04-01    52.812164
2022-04-02    42.175015
2022-04-03    56.634551
dtype: float64

In [75]:
factory01 + factory02

2022-03-25     92.512526
2022-03-26     87.261256
2022-03-27     98.570167
2022-03-28    104.581090
2022-03-29    100.381382
2022-03-30     91.430489
2022-03-31     90.208392
2022-04-01    104.142985
2022-04-02     95.383019
2022-04-03    100.326113
dtype: float64

In [76]:
factory01.index

DatetimeIndex(['2022-03-25', '2022-03-26', '2022-03-27', '2022-03-28',
               '2022-03-29', '2022-03-30', '2022-03-31', '2022-04-01',
               '2022-04-02', '2022-04-03'],
              dtype='datetime64[ns]', freq=None)

In [77]:
factory01 = pd.Series( np.random.normal(50, 5, 10) , 
                       index = [ day + timedelta(days = d) for d in range(10) ])

factory02 = pd.Series( np.random.normal(50, 5, 10) , 
                       index = [ day + timedelta(days = d+1) for d in range(10) ])

In [78]:
factory01

2022-03-25    54.749638
2022-03-26    56.398483
2022-03-27    51.111455
2022-03-28    55.841936
2022-03-29    46.341594
2022-03-30    53.749470
2022-03-31    57.426653
2022-04-01    48.332515
2022-04-02    50.529867
2022-04-03    49.844608
dtype: float64

In [79]:
factory02

2022-03-26    47.018036
2022-03-27    52.753745
2022-03-28    38.091305
2022-03-29    47.155177
2022-03-30    44.945084
2022-03-31    50.301421
2022-04-01    55.007238
2022-04-02    50.268974
2022-04-03    49.563361
2022-04-04    49.976672
dtype: float64

In [81]:
factory = factory01 + factory02

In [82]:
factory

2022-03-25           NaN
2022-03-26    103.416519
2022-03-27    103.865199
2022-03-28     93.933240
2022-03-29     93.496770
2022-03-30     98.694555
2022-03-31    107.728074
2022-04-01    103.339754
2022-04-02    100.798841
2022-04-03     99.407968
2022-04-04           NaN
dtype: float64

In [90]:
print('결측값 확인 함수 - pd.isnull() ')
print( pd.isnull(factory) )
# print( factory.isnull() ) 

print()
print( factory[ factory.isnull()  ] )

print()
print( factory[ factory.notnull()  ] )

print('결측값을 넣어줄 때 - np.NaN ')
factory['2022-04-03'] = np.NaN

결측값 확인 함수 - pd.isnull() 
2022-03-25     True
2022-03-26    False
2022-03-27    False
2022-03-28    False
2022-03-29    False
2022-03-30    False
2022-03-31    False
2022-04-01    False
2022-04-02    False
2022-04-03    False
2022-04-04     True
dtype: bool

2022-03-25   NaN
2022-04-04   NaN
dtype: float64

2022-03-26    103.416519
2022-03-27    103.865199
2022-03-28     93.933240
2022-03-29     93.496770
2022-03-30     98.694555
2022-03-31    107.728074
2022-04-01    103.339754
2022-04-02    100.798841
2022-04-03     99.407968
dtype: float64
결측값을 넣어줄 때 - np.NaN 


In [147]:
f = factory.astype('float')
f

2022-03-25           NaN
2022-03-26    103.416519
2022-03-27    103.865199
2022-03-28      93.93324
2022-03-29      93.49677
2022-03-30     98.694555
2022-03-31    107.728074
2022-04-01    103.339754
2022-04-02    100.798841
2022-04-03           NaN
2022-04-04           NaN
dtype: object

#### DataFrame 
- 행 인덱스 , 열 인덱스
- pd.DataFrame()

In [116]:
def frmInfo(df) :
    display('data - ' , df )
    print()
    print('shape   - ' , df.shape , df.shape[0] , df.shape[1])
    print('size    - ' , df.size )
    print('ndim    - ' , df.ndim)
    print('index   - ' , df.index    , type(df.index))
    print('columns - ' , df.columns  , type( df.columns ))
    print('values  - \n' , df.values , type(df.values) )

In [117]:
print('dict를 이용한 생성 - ' ) 

dict_data = {
    'col01' : [1, 2, 3],
    'col02' : [4, 5, 6],
    'col03' : [7, 8, 9],
    'col04' : [10, 11, 12],
    'col05' : [13, 14, 15]
}

tmp_df = pd.DataFrame(dict_data) 
frmInfo( tmp_df ) 

dict를 이용한 생성 - 


'data - '

col01  col02  col03  col04  col05
0      1      4      7     10     13
1      2      5      8     11     14
2      3      6      9     12     15


shape   -  (3, 5) 3 5
size    -  15
ndim    -  2
index   -  RangeIndex(start=0, stop=3, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
columns -  Index(['col01', 'col02', 'col03', 'col04', 'col05'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [[ 1  4  7 10 13]
 [ 2  5  8 11 14]
 [ 3  6  9 12 15]] <class 'numpy.ndarray'>


In [125]:
print( tmp_df['col01'] , type(tmp_df['col01']) )
print( tmp_df['col01'].index , tmp_df['col01'].values)
print( tmp_df['col01'][0] , type(tmp_df['col01'][0]) )


0    1
1    2
2    3
Name: col01, dtype: int64 <class 'pandas.core.series.Series'>
RangeIndex(start=0, stop=3, step=1) [1 2 3]
1 <class 'numpy.int64'>


In [127]:
print('리스트를 이용한 생성 - ') 
print()
tmp_df = pd.DataFrame( [ [20, 'M', False] , [30, 'F', True] ] , 
                       index   = ['섭섭해' , '임섭순'] , 
                       columns = ['나이' , '성별' , '결혼여부']) 
frmInfo(tmp_df)

리스트를 이용한 생성 - 



'data - '

나이 성별   결혼여부
섭섭해  20  M  False
임섭순  30  F   True


shape   -  (2, 3) 2 3
size    -  6
ndim    -  2
index   -  Index(['섭섭해', '임섭순'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns -  Index(['나이', '성별', '결혼여부'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [[20 'M' False]
 [30 'F' True]] <class 'numpy.ndarray'>


In [131]:
print('인덱스 이름 변경 - rename() , inplace - ') 

tmp_df.rename(columns = {'나이' : '연세' , '성별' : '남녀' , '결혼여부' : '혼인'} , inplace = True  ) 
tmp_df.rename(index   = {'섭섭해' : '이이슬' , '임섭순' : '이현호'} , inplace = True  ) 
frmInfo(tmp_df)

인덱스 이름 변경 - rename() , inplace - 


'data - '

연세 남녀     혼인
이이슬  20  M  False
이현호  30  F   True


shape   -  (2, 3) 2 3
size    -  6
ndim    -  2
index   -  Index(['이이슬', '이현호'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns -  Index(['연세', '남녀', '혼인'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [[20 'M' False]
 [30 'F' True]] <class 'numpy.ndarray'>


In [159]:
data = {
    '2022'   : [35325412 , 23535634 , 13453264  ,34242345] , 
    '2017'   : [100000, 200000 ,300000 , 400000 ] , 
    '2012'   : [1,2,3,4] ,
    '2010'   : [1,2,3,4] ,
    '지역'   : ['특별시' , '경상권' , '수도권' , '수도권'],
    '증가율' : [0.2324, 0.0434, 0.0944, 0.0034] 
}

col_idx  = ['지역' , '2010' , '2012' , '2017' , '2022' , '증가율'] 
row_idx  = ['서울' , '부산' , '경기' , '인천']

tmp_frm = pd.DataFrame(data , 
                       columns = col_idx ,
                       index   = row_idx ) 

frmInfo( tmp_frm )

'data - '

지역  2010  2012    2017      2022     증가율
서울  특별시     1     1  100000  35325412  0.2324
부산  경상권     2     2  200000  23535634  0.0434
경기  수도권     3     3  300000  13453264  0.0944
인천  수도권     4     4  400000  34242345  0.0034


shape   -  (4, 6) 4 6
size    -  24
ndim    -  2
index   -  Index(['서울', '부산', '경기', '인천'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns -  Index(['지역', '2010', '2012', '2017', '2022', '증가율'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [['특별시' 1 1 100000 35325412 0.2324]
 ['경상권' 2 2 200000 23535634 0.0434]
 ['수도권' 3 3 300000 13453264 0.0944]
 ['수도권' 4 4 400000 34242345 0.0034]] <class 'numpy.ndarray'>


In [160]:
tmp_frm.index.name   = 'city'
tmp_frm.columns.name = 'feature'
tmp_frm

feature   지역  2010  2012    2017      2022     증가율
city                                              
서울       특별시     1     1  100000  35325412  0.2324
부산       경상권     2     2  200000  23535634  0.0434
경기       수도권     3     3  300000  13453264  0.0944
인천       수도권     4     4  400000  34242345  0.0034

In [161]:
print('index name   - ' , tmp_frm.index   , tmp_frm.index.name)
print('columns name - ' , tmp_frm.columns , tmp_frm.columns.name)

index name   -  Index(['서울', '부산', '경기', '인천'], dtype='object', name='city') city
columns name -  Index(['지역', '2010', '2012', '2017', '2022', '증가율'], dtype='object', name='feature') feature


- 데이터 프레임에서 열 데이터의 갱신, 추가 , 삭제

In [163]:
print('추가 - ')
print()
tmp_frm['2017-2022 증가율'] =  ( (tmp_frm['2022'] - tmp_frm['2017']) / tmp_frm['2017'] * 100 ).round(2)
tmp_frm

feature   지역  2010  2012    2017      2022     증가율  2017-2022 증가율
city                                                             
서울       특별시     1     1  100000  35325412  0.2324       35225.41
부산       경상권     2     2  200000  23535634  0.0434       11667.82
경기       수도권     3     3  300000  13453264  0.0944        4384.42
인천       수도권     4     4  400000  34242345  0.0034        8460.59

In [164]:
print('삭제 - ')
del tmp_frm['2017-2022 증가율']
tmp_frm

삭제 - 


feature   지역  2010  2012    2017      2022     증가율
city                                              
서울       특별시     1     1  100000  35325412  0.2324
부산       경상권     2     2  200000  23535634  0.0434
경기       수도권     3     3  300000  13453264  0.0944
인천       수도권     4     4  400000  34242345  0.0034

In [168]:
tmp_subset = tmp_frm[ ['지역' , '증가율'] ] 
frmInfo(tmp_subset)

'data - '

feature   지역     증가율
city                
서울       특별시  0.2324
부산       경상권  0.0434
경기       수도권  0.0944
인천       수도권  0.0034


shape   -  (4, 2) 4 2
size    -  8
ndim    -  2
index   -  Index(['서울', '부산', '경기', '인천'], dtype='object', name='city') <class 'pandas.core.indexes.base.Index'>
columns -  Index(['지역', '증가율'], dtype='object', name='feature') <class 'pandas.core.indexes.base.Index'>
values  - 
 [['특별시' 0.2324]
 ['경상권' 0.0434]
 ['수도권' 0.0944]
 ['수도권' 0.0034]] <class 'numpy.ndarray'>


- row indexing (항상 슬라이싱을 필요로 한다.)
- 배열, 라벨 인덱싱이 가능하다

In [178]:
print('라벨 인덱싱 - ')
display( tmp_frm[ : '서울'] )

print()
print('배열 인덱싱 - ')
display( tmp_frm[ : 1] )



라벨 인덱싱 - 


feature   지역  2010  2012    2017      2022     증가율
city                                              
서울       특별시     1     1  100000  35325412  0.2324


배열 인덱싱 - 


feature   지역  2010  2012    2017      2022     증가율
city                                              
서울       특별시     1     1  100000  35325412  0.2324

In [179]:
tmp_frm

feature   지역  2010  2012    2017      2022     증가율
city                                              
서울       특별시     1     1  100000  35325412  0.2324
부산       경상권     2     2  200000  23535634  0.0434
경기       수도권     3     3  300000  13453264  0.0944
인천       수도권     4     4  400000  34242345  0.0034

In [180]:
print('행 인덱싱으로 서울 - 경기까지 필터링한다면? - ')

print('라벨 인덱싱 - ')
display( tmp_frm[ '서울' : '경기'] )

print()
print('배열 인덱싱 - ')
display( tmp_frm[ 0 : 3] )

행 인덱싱으로 서울 - 경기까지 필터링한다면? - 
라벨 인덱싱 - 


feature   지역  2010  2012    2017      2022     증가율
city                                              
서울       특별시     1     1  100000  35325412  0.2324
부산       경상권     2     2  200000  23535634  0.0434
경기       수도권     3     3  300000  13453264  0.0944


배열 인덱싱 - 


feature   지역  2010  2012    2017      2022     증가율
city                                              
서울       특별시     1     1  100000  35325412  0.2324
부산       경상권     2     2  200000  23535634  0.0434
경기       수도권     3     3  300000  13453264  0.0944

In [181]:
tmp_frm

feature   지역  2010  2012    2017      2022     증가율
city                                              
서울       특별시     1     1  100000  35325412  0.2324
부산       경상권     2     2  200000  23535634  0.0434
경기       수도권     3     3  300000  13453264  0.0944
인천       수도권     4     4  400000  34242345  0.0034

- 개별 인덱싱이 가능할까?


In [190]:
print('2022년 서울과 인천의 데이터를 필터링한다면? - ') 
print( tmp_frm['2022'][['서울' , '인천']] )
print( type( tmp_frm['2022'][['서울' , '인천']]) )

2022년 서울과 인천의 데이터를 필터링한다면? - 
city
서울    35325412
인천    34242345
Name: 2022, dtype: int64
<class 'pandas.core.series.Series'>


#### 다음 조건을 만족하는 임의의 데이터프레임을 만들어 보자 [실습]
- 열의 갯수와 행의 갯수는 각각 5개 이상이여야 한다.
- 열에는 정수, 문자열, 실수, 날짜 데이터가 각각 1개 이상 포함되어야 한다.

In [191]:
intValue = np.random.randint(1, 10, 10)
intValue

array([5, 7, 9, 6, 8, 8, 2, 2, 5, 1])

In [192]:
floatValue = np.random.rand(10)
floatValue

array([0.93605514, 0.69186049, 0.97066189, 0.72985546, 0.28563933,
       0.11043911, 0.94764396, 0.53134244, 0.05157989, 0.07007826])

In [193]:
day = datetime(2022, 3, 25)
dateValue = [ day + timedelta(d) for d in range(0,10) ] 
dateValue

[datetime.datetime(2022, 3, 25, 0, 0),
 datetime.datetime(2022, 3, 26, 0, 0),
 datetime.datetime(2022, 3, 27, 0, 0),
 datetime.datetime(2022, 3, 28, 0, 0),
 datetime.datetime(2022, 3, 29, 0, 0),
 datetime.datetime(2022, 3, 30, 0, 0),
 datetime.datetime(2022, 3, 31, 0, 0),
 datetime.datetime(2022, 4, 1, 0, 0),
 datetime.datetime(2022, 4, 2, 0, 0),
 datetime.datetime(2022, 4, 3, 0, 0)]

In [194]:
strValue = ['뭐 먹지?' , '배부르다' , '해장국' , '짬뽕' , '회덮밥' , '뭐 먹지?' , '배부르다' , '해장국' , '짬뽕' , '회덮밥' ]
strValue

['뭐 먹지?', '배부르다', '해장국', '짬뽕', '회덮밥', '뭐 먹지?', '배부르다', '해장국', '짬뽕', '회덮밥']

In [195]:
data = {
    '정수' : intValue , 
    '실수' : floatValue , 
    '날짜' : dateValue , 
    '문자' : strValue
}
tmp_frm = pd.DataFrame(data)
frmInfo(tmp_frm)

'data - '

정수        실수         날짜     문자
0   5  0.936055 2022-03-25  뭐 먹지?
1   7  0.691860 2022-03-26   배부르다
2   9  0.970662 2022-03-27    해장국
3   6  0.729855 2022-03-28     짬뽕
4   8  0.285639 2022-03-29    회덮밥
5   8  0.110439 2022-03-30  뭐 먹지?
6   2  0.947644 2022-03-31   배부르다
7   2  0.531342 2022-04-01    해장국
8   5  0.051580 2022-04-02     짬뽕
9   1  0.070078 2022-04-03    회덮밥


shape   -  (10, 4) 10 4
size    -  40
ndim    -  2
index   -  RangeIndex(start=0, stop=10, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
columns -  Index(['정수', '실수', '날짜', '문자'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [[5 0.9360551449918639 Timestamp('2022-03-25 00:00:00') '뭐 먹지?']
 [7 0.691860490979982 Timestamp('2022-03-26 00:00:00') '배부르다']
 [9 0.9706618932841099 Timestamp('2022-03-27 00:00:00') '해장국']
 [6 0.7298554581193258 Timestamp('2022-03-28 00:00:00') '짬뽕']
 [8 0.2856393342048177 Timestamp('2022-03-29 00:00:00') '회덮밥']
 [8 0.11043910932601364 Timestamp('2022-03-30 00:00:00') '뭐 먹지?']
 [2 0.947643963946241 Timestamp('2022-03-31 00:00:00') '배부르다']
 [2 0.5313424437420725 Timestamp('2022-04-01 00:00:00') '해장국']
 [5 0.05157989299649923 Timestamp('2022-04-02 00:00:00') '짬뽕']
 [1 0.07007825504499798 Timestamp('2022-04-03 00:00:00') '회덮밥']] <class 'numpy.ndarray'>


#### booklist_json.json 파일로부터 데이터를 읽어서 데이터프레임을 만들어 보자[실습]
- json.loads() : json으로 된 문자열 파일을 읽어들이 때
- json.load()  : json 파일을 읽어들일 때

In [208]:
with open('./pandas_data/booklist_json.json' , 'r' , encoding='utf-8') as file :
    books = json.load(file)

print('books type - ' , type(books))
# print(books)

print()
book_frm = pd.DataFrame(books) 
frmInfo(book_frm)

books type -  <class 'list'>



'data - '

bookName  \
0                               나는 꼭 필요한 것만 남기기로 했다   
1                          파이썬과 대스크를 활용한 고성능 데이터 분석   
2                                        웹어셈블리 인 액션   
3                               쉽게 배워 바로 써먹는 디자인 패턴   
4                                             부의 원칙   
5                                    만들면서 배우는 픽셀 아트   
6                               초보자를 위한 언리얼 엔진 4 입문   
7                                           분산원장 기술   
8                       회사에서 바로 통하는 3ds Max + V-Ray   
9                      재미있고 빠른 한글 쓰기 3권 : 교과서 쉬운 낱말   
10                           나도 초록 식물 잘 키우면 소원이 없겠네   
11         IT CookBook, 액세스 2019로 배우는 데이터베이스 기초와 실습   
12                                         GAN 인 액션   
13                       재미있고 빠른 어휘력 동화 – 아지랑이가 뭐야?   
14                     재미있고 빠른 어휘력 동화 – 많다의 반대가 뭐야?   
15                          만화로 보는 바빌론 부자들의 돈 버는 지혜   
16                                      포르잔 C++ 바이블   
17                                  청소년 인문학 수업 - 1권   
18                                  청소년 인문학 수업 - 2권   
19                          처음 시작하는 파이썬&#40;2판&#41;   
20                              퀀트 전략을 위한 인공지능 트레이딩   
21                                      처음 시작하는 딥러닝   
22                        회사에서 바로 통하는 실무 엑셀 매크로&VBA   
23                                            게임 오버   
24                                  초소형 머신러닝 TinyML   
25                                   오늘도 뇌는 거짓말을 한다   
26                                허팝만 따라 해봐! 유튜브 정석   
27                      이것이 취업을 위한 코딩 테스트다 with 파이썬   
28                                    딥러닝을 위한 선형대수학   
29                                          유닉스의 탄생   
30                   회사에서 바로 통하는  오토캐드 AutoCAD 2021   
31  IT CookBook, 오라클로 배우는 데이터베이스 개론과 실습&#40;2판&#41;   
32                                       별, 걔 다 그립네   
33                                   대학을 버려야 대학이 산다   
34                    IT CookBook, 따라 하면서 배우는 사물인터넷   
35               재미있고 빠른 첫 한글 준비 선 긋기1권 직선∙곡선∙자음∙모음   
36                           재미있고 빠른 첫 한글 4권 쌍자음∙받침   
37                                       핸즈온 비지도 학습   
38                    재미있고 빠른 첫 한글 쓰기1권 모음∙자음∙쉬운 낱말   
39                                      우리 아이 처음 놀이   
40                       미라클 모닝 기적의 공식&#40;개정판&#41;   
41                             창의적 공학설계&#40;3판&#41;   
42                  R로 하는 다변량 데이터 분석 : 이론부터 실무 활용까지   
43          공학 핵심수학&#40;2판&#41;  : 기초부터 심화까지 핵심만 쏙쏙   
44           응용이 보이는 선형대수학 : 파이썬과 함께하는 선형대수학 이론과 응용   
45                                    파이썬 증권 데이터 분석   
46                             나의 첫 파이썬&#40;2판&#41;   
47                                    나는 왜 네 말이 힘들까   
48                         혼자 공부하는 첫 프로그래밍 with 파이썬   
49                                 퇴근길 인문학 수업 : 뉴노멀   

                                                 link  
0   http://www.hanbit.co.kr/store/books/look.php?p...  
1   http://www.hanbit.co.kr/store/books/look.php?p...  
2   http://www.hanbit.co.kr/store/books/look.php?p...  
3   http://www.hanbit.co.kr/store/books/look.php?p...  
4   http://www.hanbit.co.kr/store/books/look.php?p...  
5   http://www.hanbit.co.kr/store/books/look.php?p...  
6   http://www.hanbit.co.kr/store/books/look.php?p...  
7   http://www.hanbit.co.kr/store/books/look.php?p...  
8   http://www.hanbit.co.kr/store/books/look.php?p...  
9   http://www.hanbit.co.kr/store/books/look.php?p...  
10  http://www.hanbit.co.kr/store/books/look.php?p...  
11  http://www.hanbit.co.kr/store/books/look.php?p...  
12  http://www.hanbit.co.kr/store/books/look.php?p...  
13  http://www.hanbit.co.kr/store/books/look.php?p...  
14  http://www.hanbit.co.kr/store/books/look.php?p...  
15  http://www.hanbit.co.kr/store/books/look.php?p...  
16  http://www.hanbit.co.kr/store/books/look.php?p...  
17  http://www.hanbit.co.kr/store/books/look.php?p...  
18  http://www.hanbit.co.kr/store/books/look.php?p...  
19  http://www.hanbit.co.kr/store/books/look.php?p...  
20  http://www.hanbit.co.kr/store/books/look.php?p...  
21  h


shape   -  (50, 2) 50 2
size    -  100
ndim    -  2
index   -  RangeIndex(start=0, stop=50, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
columns -  Index(['bookName', 'link'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [['나는 꼭 필요한 것만 남기기로 했다'
  'http://www.hanbit.co.kr/store/books/look.php?p_code=B7269609529']
 ['파이썬과 대스크를 활용한 고성능 데이터 분석'
  'http://www.hanbit.co.kr/store/books/look.php?p_code=B4595034178']
 ['웹어셈블리 인 액션'
  'http://www.hanbit.co.kr/store/books/look.php?p_code=B5654500071']
 ['쉽게 배워 바로 써먹는 디자인 패턴'
  'http://www.hanbit.co.kr/store/books/look.php?p_code=B9696096335']
 ['부의 원칙'
  'http://www.hanbit.co.kr/store/books/look.php?p_code=B1303121763']
 ['만들면서 배우는 픽셀 아트'
  'http://www.hanbit.co.kr/store/books/look.php?p_code=B8144473464']
 ['초보자를 위한 언리얼 엔진 4 입문'
  'http://www.hanbit.co.kr/store/books/look.php?p_code=B4792640793']
 ['분산원장 기술'
  'http://www.hanbit.co.kr/store/books/look.php?p_code=B2916452728']
 ['회사에서 바로 통하는 3ds Max + V-Ray'
  '


#### url을 이용한 json 파일로부터 데이터를 읽어서 데이터프레임을 만들어 보자[실습]
- https://www.kobis.or.kr/kobisopenapi/homepg/apiservice/searchServiceInfo.do?serviceId=searchDailyBoxOffice

In [219]:
url = 'http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=f5eef3421c602c6cb7ea224104795888&targetDt=20120101'
response = urllib.request.urlopen(url)
# print('response - ' , response.read())
# rank , movieNm , salesAmt

json_data = json.loads(response.read())
print('type - ', type(json_data))
print()
# print(json_data)

data = json_data['boxOfficeResult']['dailyBoxOfficeList']
print(data)

ranks  = []
movies = [] 
amts   = []

for d in data :
    ranks.append(d['rank'])
    movies.append(d['movieNm'])
    amts.append(d['salesAmt'])

data_dict = {
    'rank'   : ranks , 
    'title'  : movies , 
    'amount' : amts  
}    

tmp_frm = pd.DataFrame(data_dict)
frmInfo(tmp_frm)

type -  <class 'dict'>

[{'rnum': '1', 'rank': '1', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20112207', 'movieNm': '미션임파서블:고스트프로토콜', 'openDt': '2011-12-15', 'salesAmt': '2776060500', 'salesShare': '36.3', 'salesInten': '-415699000', 'salesChange': '-13', 'salesAcc': '40541108500', 'audiCnt': '353274', 'audiInten': '-60106', 'audiChange': '-14.5', 'audiAcc': '5328435', 'scrnCnt': '697', 'showCnt': '3223'}, {'rnum': '2', 'rank': '2', 'rankInten': '1', 'rankOldAndNew': 'OLD', 'movieCd': '20110295', 'movieNm': '마이 웨이', 'openDt': '2011-12-21', 'salesAmt': '1189058500', 'salesShare': '15.6', 'salesInten': '-105894500', 'salesChange': '-8.2', 'salesAcc': '13002897500', 'audiCnt': '153501', 'audiInten': '-16465', 'audiChange': '-9.7', 'audiAcc': '1739543', 'scrnCnt': '588', 'showCnt': '2321'}, {'rnum': '3', 'rank': '3', 'rankInten': '-1', 'rankOldAndNew': 'OLD', 'movieCd': '20112621', 'movieNm': '셜록홈즈 : 그림자 게임', 'openDt': '2011-12-21', 'salesAmt': '1176022500', 'salesShare': '15.4

'data - '

rank                                title      amount
0    1                       미션임파서블:고스트프로토콜  2776060500
1    2                                마이 웨이  1189058500
2    3                        셜록홈즈 : 그림자 게임  1176022500
3    4                               퍼펙트 게임   644532000
4    5                        프렌즈: 몬스터섬의비밀    436753500
5    6                                라이온 킹   507115500
6    7                               오싹한 연애   344871000
7    8   극장판 포켓몬스터 베스트 위시「비크티니와 백의 영웅 레시라무」   167809500
8    9                            앨빈과 슈퍼밴드3   137030000
9   10  극장판 포켓몬스터 베스트 위시 「비크티니와 흑의 영웅 제크로무」   125535500


shape   -  (10, 3) 10 3
size    -  30
ndim    -  2
index   -  RangeIndex(start=0, stop=10, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
columns -  Index(['rank', 'title', 'amount'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [['1' '미션임파서블:고스트프로토콜' '2776060500']
 ['2' '마이 웨이' '1189058500']
 ['3' '셜록홈즈 : 그림자 게임' '1176022500']
 ['4' '퍼펙트 게임' '644532000']
 ['5' '프렌즈: 몬스터섬의비밀 ' '436753500']
 ['6' '라이온 킹' '507115500']
 ['7' '오싹한 연애' '344871000']
 ['8' '극장판 포켓몬스터 베스트 위시「비크티니와 백의 영웅 레시라무」' '167809500']
 ['9' '앨빈과 슈퍼밴드3' '137030000']
 ['10' '극장판 포켓몬스터 베스트 위시 「비크티니와 흑의 영웅 제크로무」' '125535500']] <class 'numpy.ndarray'>
